### ISSUE TITLE
MessagesViewController

### ISSUE THREAD

**Issue by jlems** [kierk/aggle#3]
The TabBar at the bottom will have to be moved elsewhere because it blocks where the user has to click to start typing into the chatbox. Maybe add a button that takes you back to the sell screen or something.

**Comment by eugenekolo** [comment]
I imagined no toolbar on msg screen. Just a back btn at too

**Comment by jlems** [comment]
Someone should implement this today in class.

**Comment by eugenekolo** [comment]
done
